import { ScenarioConfig } from './types';

export const SCENARIOS: ScenarioConfig[] = [
  {
    id: 'basic',
    name: '基础难度',
    level: '基础',
    width: 10,
    height: 10,
    obstacleDensity: 0,
    obstacleMode: 'block',
    foodCount: 1,
    foodTTL: Infinity,
    timeBudgetMs: 5,
    runnable: true,
    description: '10×10 无障碍，单食物随机生成、不过期。决策预算 5ms/步。',
  },
  {
    id: 'medium',
    name: '中等难度 A（宏格障碍）',
    level: '中等',
    width: 16,
    height: 16,
    obstacleDensity: 0.08,
    obstacleMode: 'block',
    foodCount: 1,
    foodTTL: Infinity,
    timeBudgetMs: 10,
    runnable: true,
    description: '16×16，约 8% 随机障碍（2×2 宏格对齐、保证连通），单食物随机生成。哈密顿回路可通过“宏格生成树法”改造后成立。决策预算 10ms/步。',
  },
  {
    id: 'medium-cell',
    name: '中等难度 B（单格障碍）',
    level: '中等',
    width: 15,
    height: 15,
    obstacleDensity: 0.08,
    obstacleMode: 'cell',
    foodCount: 1,
    foodTTL: Infinity,
    timeBudgetMs: 10,
    runnable: true,
    description: '15×15，8% 任意单格随机障碍（无死胡同、保证连通），单食物随机生成。一般不存在哈密顿回路，用于测试搜索类策略极限。决策预算 10ms/步。',
  },
  {
    id: 'hard',
    name: '困难难度 A（宏格障碍 + 多食物 + 有效期）',
    level: '困难',
    width: 20,
    height: 20,
    obstacleDensity: 0.08,
    obstacleMode: 'block',
    foodCount: 3,
    foodTTL: 200,
    timeBudgetMs: 16,
    runnable: true,
    description: '20×20，约 8% 宏格障碍，同时 3 个食物，食物有效期 200 步。决策预算 16ms/步（一帧）。',
  },
  {
    id: 'hard-cell',
    name: '困难难度 B（单格障碍 + 多食物 + 有效期）',
    level: '困难',
    width: 20,
    height: 20,
    obstacleDensity: 0.08,
    obstacleMode: 'cell',
    foodCount: 3,
    foodTTL: 200,
    timeBudgetMs: 16,
    runnable: true,
    description: '20×20，8% 任意单格障碍，同时 3 个食物，食物有效期 200 步。用于评估搜索类策略在大图上的上限。决策预算 16ms/步。',
  },
  {
    id: 'extreme',
    name: '极限难度（仅设计方案）',
    level: '极限',
    width: 30,
    height: 30,
    obstacleDensity: 0.1,
    obstacleMode: 'cell',
    foodCount: 5,
    foodTTL: 80,
    timeBudgetMs: 2,
    runnable: false,
    description: '30×30 及以上，动态障碍（周期性出现/移动），5 个食物、有效期 80 步，决策预算 2ms/步。本程序不提供可运行实现，仅给出设计与可行性分析。',
  },
  {
    id: 'extreme-dyn',
    name: '极限难度 A（动态宏格障碍，A1 对手档）',
    level: '极限',
    width: 30,
    height: 30,
    obstacleDensity: 0.08,
    obstacleMode: 'block',
    foodCount: 5,
    foodTTL: 80,
    timeBudgetMs: 2,
    runnable: true,
    dynamicObstacles: true,
    dynCount: 2,
    dynPeriod: 40,
    dynNotice: 15,
    description: '30×30，约 8% 宏格障碍（初始静态），每 40 步最多 2 块宏格变动（出现带 15 步预约位预告），5 食物、有效期 80 步、2ms/步。A1 对手档：可拒绝危险候选。推荐 hamilton-dyn 策略。',
  },
  {
    id: 'extreme-dyn-a2',
    name: '极限难度 A2（动态宏格障碍，事件必须落地）',
    level: '极限',
    width: 30,
    height: 30,
    obstacleDensity: 0.08,
    obstacleMode: 'block',
    foodCount: 5,
    foodTTL: 80,
    timeBudgetMs: 2,
    runnable: true,
    dynamicObstacles: true,
    dynCount: 2,
    dynPeriod: 40,
    dynNotice: 15,
    forceLand: true,
    description: 'A2 对手档：障碍承诺必须落地（落在蛇头正前方亦可，不落蛇身），调度器不可拒绝候选；接受时做公平性三条件检查（逃逸集非空且 ≥2、T≥2、落地后连通且偶格）。注：设计稿中的「逃逸承诺」锁死模式未实装，当前通关由三条件 + 常规回路维护支撑。通关率仅记录不预设 100%。',
  } as ScenarioConfig,
];

export function getScenario(id: string): ScenarioConfig {
  return SCENARIOS.find((s) => s.id === id) ?? SCENARIOS[0];
}
